[device.test_daq]
averages = 100
device_name = "test_daq"
gate_time = 1000
trace = true

[device.test_daq.data.counts]
data = [
    1027.116294050521,
    988.3672306501855,
    986.1165674472734,
    928.6071931160028,
    1034.5807409480256,
    987.8734313517084,
]
unit = "dimensionless"

[device.test_daq.data."current (mA)"]
data = [
    8017.7394642432255,
    6512.527958480107,
    239.7195325170582,
    4663.665986621474,
    9516.699793574244,
    1965.4969537854124,
]
unit = "mA"

[device.test_daq.data."trace (signal)"]
data = [
    [
    1.0447978417018071,
    0.7727735979680339,
    0.38774221621882177,
    0.15081023553049577,
    0.22320469234020676,
    0.1361104981121352,
    -0.02934807870996943,
    -0.013789665345424616,
    0.1616910489682895,
    0.08676671720620804,
    0.02909000882522548,
    -0.1036623430440693,
    -0.09019043546625448,
    0.07151132365087477,
    -0.06615129854058202,
    -0.04667653814372204,
    -0.10675659498329496,
    0.026895290370905947,
    0.1217080991106212,
    -0.0944186297320937,
],
    [
    0.9700759125200246,
    0.4921343835986874,
    0.24267081993392783,
    0.010863893830240027,
    0.053132887334485665,
    0.04978939669346478,
    0.09845027696040012,
    0.11901337518733424,
    -0.03576431090549567,
    -0.1206942480846184,
    0.21579557412691505,
    -0.18715165972947265,
    -0.06262401050297492,
    0.008511653868633227,
    0.03321337665594366,
    -0.11178028656841416,
    -0.17064547937477398,
    0.03161139319308289,
    -0.14274590787066485,
    -0.0060312674910923385,
],
    [
    1.0188536119402738,
    0.6637152844648913,
    0.4210585492866937,
    0.36927779015331275,
    0.019117680315903468,
    0.19468828594402532,
    0.07336207647584278,
    -0.022174301531578972,
    -0.0303436024236532,
    -0.21968029370669467,
    0.10420757419410503,
    -0.06113823445580752,
    0.02573004653103607,
    0.12213452659444472,
    -0.22287246303912833,
    0.041310989053731824,
    -0.1006489365805512,
    -0.01235719293590365,
    0.02730117475736327,
    -0.0924166723745084,
],
    [
    1.060702996814411,
    0.5081400893891936,
    0.3961354893668618,
    0.12304619017126334,
    0.09174317086881496,
    0.11991096304350106,
    0.07704895694489852,
    0.1966070612353756,
    0.05650363600401107,
    -0.22201449702388187,
    -0.06050649126033778,
    0.011150496844053764,
    0.12344139523802317,
    -0.01765496502368657,
    -0.04457741136011155,
    -0.08770417458771812,
    -0.13608583749150965,
    0.02553337602539765,
    0.14956487470292848,
    0.2053330174268458,
],
    [
    1.05995641726433,
    0.6373683592199112,
    0.5297141178100202,
    0.1858763666698396,
    0.024369534513641808,
    -0.1310345639339091,
    0.011932215780998914,
    -0.08861656380061453,
    0.07034388176672676,
    -0.06895627952307277,
    -0.019407263520548036,
    0.05116122445231286,
    -0.06088474118183261,
    0.06286323608082442,
    0.00668522950953493,
    0.07845138544777507,
    -0.02405086910970364,
    0.08543270602372598,
    0.01948510204982236,
    0.031855525428942696,
],
    [
    0.9685919728005424,
    0.6355562932142825,
    0.38098939700458584,
    0.1512563195587169,
    0.05398250452096728,
    0.20379509270590743,
    0.13508641855216022,
    -0.04982043566102058,
    -0.021952801151160543,
    -0.08140587803053224,
    -0.2142685014090404,
    0.13233414287393055,
    0.0699547242331748,
    -0.04381870004171965,
    0.07514026060747604,
    0.2011905144577405,
    0.13735326438332396,
    -0.09469323573787292,
    -0.010503329514604356,
    0.054916464766419586,
],
]
unit = "V"

[device.test_daq.data."trace (time (s))"]
data = [
    [
    0.0,
    0.5263157894736842,
    1.0526315789473684,
    1.5789473684210529,
    2.1052631578947367,
    2.631578947368421,
    3.1578947368421053,
    3.6842105263157894,
    4.2105263157894735,
    4.7368421052631575,
    5.263157894736842,
    5.789473684210526,
    6.315789473684211,
    6.842105263157895,
    7.368421052631579,
    7.894736842105263,
    8.421052631578947,
    8.947368421052632,
    9.473684210526317,
    10.0,
],
    [
    0.0,
    0.5263157894736842,
    1.0526315789473684,
    1.5789473684210529,
    2.1052631578947367,
    2.631578947368421,
    3.1578947368421053,
    3.6842105263157894,
    4.2105263157894735,
    4.7368421052631575,
    5.263157894736842,
    5.789473684210526,
    6.315789473684211,
    6.842105263157895,
    7.368421052631579,
    7.894736842105263,
    8.421052631578947,
    8.947368421052632,
    9.473684210526317,
    10.0,
],
    [
    0.0,
    0.5263157894736842,
    1.0526315789473684,
    1.5789473684210529,
    2.1052631578947367,
    2.631578947368421,
    3.1578947368421053,
    3.6842105263157894,
    4.2105263157894735,
    4.7368421052631575,
    5.263157894736842,
    5.789473684210526,
    6.315789473684211,
    6.842105263157895,
    7.368421052631579,
    7.894736842105263,
    8.421052631578947,
    8.947368421052632,
    9.473684210526317,
    10.0,
],
    [
    0.0,
    0.5263157894736842,
    1.0526315789473684,
    1.5789473684210529,
    2.1052631578947367,
    2.631578947368421,
    3.1578947368421053,
    3.6842105263157894,
    4.2105263157894735,
    4.7368421052631575,
    5.263157894736842,
    5.789473684210526,
    6.315789473684211,
    6.842105263157895,
    7.368421052631579,
    7.894736842105263,
    8.421052631578947,
    8.947368421052632,
    9.473684210526317,
    10.0,
],
    [
    0.0,
    0.5263157894736842,
    1.0526315789473684,
    1.5789473684210529,
    2.1052631578947367,
    2.631578947368421,
    3.1578947368421053,
    3.6842105263157894,
    4.2105263157894735,
    4.7368421052631575,
    5.263157894736842,
    5.789473684210526,
    6.315789473684211,
    6.842105263157895,
    7.368421052631579,
    7.894736842105263,
    8.421052631578947,
    8.947368421052632,
    9.473684210526317,
    10.0,
],
    [
    0.0,
    0.5263157894736842,
    1.0526315789473684,
    1.5789473684210529,
    2.1052631578947367,
    2.631578947368421,
    3.1578947368421053,
    3.6842105263157894,
    4.2105263157894735,
    4.7368421052631575,
    5.263157894736842,
    5.789473684210526,
    6.315789473684211,
    6.842105263157895,
    7.368421052631579,
    7.894736842105263,
    8.421052631578947,
    8.947368421052632,
    9.473684210526317,
    10.0,
],
]
unit = "s"

[device.test_daq.timestamps]
counts = [
    "2026-01-16T06:35:32.423257Z",
    "2026-01-16T06:35:37.432315Z",
    "2026-01-16T06:35:42.439905Z",
    "2026-01-16T06:35:47.446399Z",
    "2026-01-16T06:35:52.449978Z",
    "2026-01-16T06:35:57.456367Z",
]
"current (mA)" = [
    "2026-01-16T06:35:32.423257Z",
    "2026-01-16T06:35:37.432315Z",
    "2026-01-16T06:35:42.439905Z",
    "2026-01-16T06:35:47.446399Z",
    "2026-01-16T06:35:52.449978Z",
    "2026-01-16T06:35:57.456367Z",
]
"trace (signal)" = [
    "2026-01-16T06:35:32.423257Z",
    "2026-01-16T06:35:37.432315Z",
    "2026-01-16T06:35:42.439905Z",
    "2026-01-16T06:35:47.446399Z",
    "2026-01-16T06:35:52.449978Z",
    "2026-01-16T06:35:57.456367Z",
]
"trace (time (s))" = [
    "2026-01-16T06:35:32.423257Z",
    "2026-01-16T06:35:37.432315Z",
    "2026-01-16T06:35:42.439905Z",
    "2026-01-16T06:35:47.446399Z",
    "2026-01-16T06:35:52.449978Z",
    "2026-01-16T06:35:57.456367Z",
]

[device.test_daq2]
averages = 100
device_name = "test_daq2"
gate_time = 1000
trace = true

[device.test_daq2.data.counts]
data = [
    1006.4248230217106,
    931.7399973963674,
    936.7787546483152,
    963.5567794933309,
    944.1138395659576,
    1057.1551336415373,
]
unit = "dimensionless"

[device.test_daq2.data."current (mA)"]
data = [
    1092.575545513814,
    8241.554223604464,
    3879.7693657873265,
    6105.30605897467,
    3058.5963794841164,
    10076.704811064976,
]
unit = "mA"

[device.test_daq2.data."trace (signal)"]
data = [
    [
    0.8475570105618825,
    0.4931949424455993,
    0.37784028582009493,
    0.1703305489519783,
    0.21004330301138183,
    0.08114886637724587,
    0.0535169266919009,
    -0.1248503818832657,
    0.031895085933298345,
    0.04550275907011136,
    0.0795416564903485,
    -0.04954196262581638,
    -0.033285040972747815,
    0.03140255840616297,
    -0.09618161266085246,
    -0.11028304597396273,
    0.1481427736694035,
    -0.07431211705718999,
    -0.0619679169723351,
    0.07959879471928605,
],
    [
    1.0132824561365323,
    0.5701585172079945,
    0.359870926768106,
    0.10634258826937598,
    0.06553500106442331,
    -0.08453005346789337,
    0.17168482293718484,
    0.19334227350966848,
    0.05815575125987277,
    0.019871851232797243,
    -0.1505561742671898,
    -0.04078171224599602,
    0.0914856043524232,
    -0.20854377310242045,
    0.1433089451811305,
    0.01236002932600547,
    0.20474418610433748,
    -0.1055666551225902,
    0.10550901696284672,
    -0.06862599493940405,
],
    [
    1.0118837769990987,
    0.5574893722914896,
    0.35765515233824047,
    0.26132198781471183,
    0.05377191645840067,
    0.12328463224396202,
    -0.00481794996073652,
    -0.007890232899153516,
    -0.17600344035251933,
    0.02465690057418434,
    0.12053237048158184,
    -0.00351729575014628,
    0.010193945114732173,
    0.06569627103638383,
    -0.05184712345328912,
    -0.04936326317066324,
    0.021096483229240345,
    -0.12944997905953462,
    -0.03419473692213086,
    -0.1332070150553674,
],
    [
    0.8828726718958386,
    0.4282602035206087,
    0.3377596912164177,
    0.07920465108757299,
    0.1986319870415512,
    -0.0848008709083518,
    -0.029364627813359245,
    -0.013577939190597455,
    0.0630613229423142,
    0.03653036993096223,
    0.1646708712822415,
    0.19403556127159569,
    -0.011140480582626644,
    0.09854321619942258,
    -0.018446229722470488,
    0.048534756824001594,
    -0.3236933349224869,
    0.10217236242982948,
    0.10308850477884596,
    -0.027181572389853095,
],
    [
    1.0404585150368777,
    0.6116513646218571,
    0.5123743475954219,
    0.2945860483674115,
    0.150410847497007,
    -0.057790737126476546,
    0.19308949560460864,
    0.19267078866138268,
    0.013319381970491616,
    0.04770266493182377,
    0.003709034472500004,
    0.0952759195879696,
    -0.06761781828065234,
    0.1036982863287294,
    0.13667373613130493,
    0.31888046034855416,
    -0.0575507389072958,
    0.135600921987764,
    -0.05889348706269356,
    0.14345029058633268,
],
    [
    0.972711087443186,
    0.7344188863702507,
    0.28842594602180566,
    0.1744890820970033,
    0.24631405146325844,
    0.06345479941777342,
    0.03270397648964539,
    -0.12979646246055193,
    0.11038202572126173,
    0.050028176865034725,
    0.012073916650034868,
    0.007092117656700637,
    -0.08231809503970436,
    0.049486260615499655,
    -0.09234427861645352,
    -0.05878657678439776,
    0.17001953128912084,
    0.26546656206691027,
    -0.048690014083312715,
    -0.10917696865973069,
],
]
unit = "V"

[device.test_daq2.data."trace (time (s))"]
data = [
    [
    0.0,
    0.5263157894736842,
    1.0526315789473684,
    1.5789473684210529,
    2.1052631578947367,
    2.631578947368421,
    3.1578947368421053,
    3.6842105263157894,
    4.2105263157894735,
    4.7368421052631575,
    5.263157894736842,
    5.789473684210526,
    6.315789473684211,
    6.842105263157895,
    7.368421052631579,
    7.894736842105263,
    8.421052631578947,
    8.947368421052632,
    9.473684210526317,
    10.0,
],
    [
    0.0,
    0.5263157894736842,
    1.0526315789473684,
    1.5789473684210529,
    2.1052631578947367,
    2.631578947368421,
    3.1578947368421053,
    3.6842105263157894,
    4.2105263157894735,
    4.7368421052631575,
    5.263157894736842,
    5.789473684210526,
    6.315789473684211,
    6.842105263157895,
    7.368421052631579,
    7.894736842105263,
    8.421052631578947,
    8.947368421052632,
    9.473684210526317,
    10.0,
],
    [
    0.0,
    0.5263157894736842,
    1.0526315789473684,
    1.5789473684210529,
    2.1052631578947367,
    2.631578947368421,
    3.1578947368421053,
    3.6842105263157894,
    4.2105263157894735,
    4.7368421052631575,
    5.263157894736842,
    5.789473684210526,
    6.315789473684211,
    6.842105263157895,
    7.368421052631579,
    7.894736842105263,
    8.421052631578947,
    8.947368421052632,
    9.473684210526317,
    10.0,
],
    [
    0.0,
    0.5263157894736842,
    1.0526315789473684,
    1.5789473684210529,
    2.1052631578947367,
    2.631578947368421,
    3.1578947368421053,
    3.6842105263157894,
    4.2105263157894735,
    4.7368421052631575,
    5.263157894736842,
    5.789473684210526,
    6.315789473684211,
    6.842105263157895,
    7.368421052631579,
    7.894736842105263,
    8.421052631578947,
    8.947368421052632,
    9.473684210526317,
    10.0,
],
    [
    0.0,
    0.5263157894736842,
    1.0526315789473684,
    1.5789473684210529,
    2.1052631578947367,
    2.631578947368421,
    3.1578947368421053,
    3.6842105263157894,
    4.2105263157894735,
    4.7368421052631575,
    5.263157894736842,
    5.789473684210526,
    6.315789473684211,
    6.842105263157895,
    7.368421052631579,
    7.894736842105263,
    8.421052631578947,
    8.947368421052632,
    9.473684210526317,
    10.0,
],
    [
    0.0,
    0.5263157894736842,
    1.0526315789473684,
    1.5789473684210529,
    2.1052631578947367,
    2.631578947368421,
    3.1578947368421053,
    3.6842105263157894,
    4.2105263157894735,
    4.7368421052631575,
    5.263157894736842,
    5.789473684210526,
    6.315789473684211,
    6.842105263157895,
    7.368421052631579,
    7.894736842105263,
    8.421052631578947,
    8.947368421052632,
    9.473684210526317,
    10.0,
],
]
unit = "s"

[device.test_daq2.timestamps]
counts = [
    "2026-01-16T06:35:32.423583Z",
    "2026-01-16T06:35:37.433699Z",
    "2026-01-16T06:35:42.440775Z",
    "2026-01-16T06:35:47.446799Z",
    "2026-01-16T06:35:52.450765Z",
    "2026-01-16T06:35:57.456739Z",
]
"current (mA)" = [
    "2026-01-16T06:35:32.423583Z",
    "2026-01-16T06:35:37.433699Z",
    "2026-01-16T06:35:42.440775Z",
    "2026-01-16T06:35:47.446799Z",
    "2026-01-16T06:35:52.450765Z",
    "2026-01-16T06:35:57.456739Z",
]
"trace (signal)" = [
    "2026-01-16T06:35:32.423583Z",
    "2026-01-16T06:35:37.433699Z",
    "2026-01-16T06:35:42.440775Z",
    "2026-01-16T06:35:47.446799Z",
    "2026-01-16T06:35:52.450765Z",
    "2026-01-16T06:35:57.456739Z",
]
"trace (time (s))" = [
    "2026-01-16T06:35:32.423583Z",
    "2026-01-16T06:35:37.433699Z",
    "2026-01-16T06:35:42.440775Z",
    "2026-01-16T06:35:47.446799Z",
    "2026-01-16T06:35:52.450765Z",
    "2026-01-16T06:35:57.456739Z",
]

[session]
UUID = "230a9337-0f16-4677-b03d-1d4b360ade4f"
end_time = "16-01-2026 19:36:02.532"
start_time = "16-01-2026 19:35:32.421"

[session.info]
email = "test@example.com"
name = "John Doe"
session_description = "This is a test"
session_name = "Test"

[session.info.meta]
addtional_important_info = "This really is a test"
